name: Jest Tests

on:
  push:
    paths:
      - "client/**"
  pull_request:
    paths:
      - "client/**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run Jest tests
        working-directory: ./client
        run: bunx jest
